name: Build

permissions:
  contents: write
  id-token: write
  attestations: write

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      should_release:
        description: "Create release?"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      attestation-url: ${{ steps.attest.outputs.attestation-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MAPI
        uses: BadMagic100/setup-hk@v2
        with:
          apiPath: API
          #dependencyFilePath: $projectname$/ModDependencies.txt

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Prepare artifacts for release
        uses: actions/upload-artifact@v4
        with:
          name: Publish
          path: $projectname$/bin/Publish

      - name: Generate attestation
        id: attest
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.should_release == 'true'
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: $projectname$/bin/Publish/$safeprojectname$.zip
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    # only make a release if we manually request the build - other builds will be handled automatically with a push
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.should_release == 'true'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Get build details
        id: details
        # this assumes that an MSBuild task writes the mod version (usually the same as the assembly version) 
        # to version.txt. The contents of this file is read to step outputs for use in release
        run: |
          ver=$(sed '1s/\xEF\xBB\xBF//' < artifacts/Publish/VERSION.txt)
          echo "buildVersion=$ver" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          tag_name: v${{ steps.details.outputs.buildVersion }}
          body: |
            Build attested at ${{ needs.build.outputs.attestation-url }}
          files: |
            artifacts/Publish/$safeprojectname$.zip
